### ISSUE TITLE
degree glyph missing in GFX

### ISSUE THREAD

**Issue by ftlpilot** [ropg/truetype2gfx#17]
The degree glyph (0xb0) is missing in the GFX  font .h file - BUT - it's definitely in the ttf file (and it works in other GFX fonts I have) ??

**Comment by ropg** [comment]
My tool only turns a fixed range of codepoints from the TTF into bitmaps. I think, IIRC, that the Adafruit tool has a way to provide the beginning and end of that range (but only one range), but my tool provides no way to set these. Maybe I'll work on this at some point, but there's been so many developments since I'd have to really read up.

**Comment by ftlpilot** [comment]
Thankx - as I progressed deeper into it, I found that fontConvert only works on glyphs 0-127, so the degree symbol, 0xb0, gets lost - quite annoyingly short-sighted on AdaFruit's part IMHO. I may even have to (shudder) write my own convert utility, although I kludged a workaround degree symbol by using a smaller font's 'o'.
