### ISSUE TITLE
Fonts larger than a certain size produce incorrect output

### ISSUE THREAD

**Issue by bitbank2** [ropg/truetype2gfx#18]
Adafruit's GFXglyph structure has an inherent limitation - it uses signed 8-bit values for the font sizes and offsets. There's no reason to limit these values to 8 bits. Your font generation tool overflows these values (negative offsets become positive) when working with large fonts (e.g. > 90pt). For my own code (bb_spi_lcd library), I switched the GFXglyph structure to use 16-bit signed values and have been manually correcting the overflowed numbers generated by your tool. Can you correct your structure definitions to use 16-bit values to allow handling of very large fonts?

**Comment by ropg** [comment]
I built this six years ago as a tool to simplify creating fonts for devices with small screens. Am not up enough on current font tools and display libraries to judge whether seriously updating the work makes sense. As I don't really program in PHP anymore if I can avoid it, any serious new development would probably happen in python or javascript.

That said, if just expanding the range of characters is all you need, and if you provide a Pull Request that modifies my code for use with some special version of the Adafruit library I'll incorporate that and use it for my web tool instead of what's there now. The more ready-to-go it all is, the faster I can modify my end.

**Comment by bitbank2** [comment]
I appreciate your situation and  thank you for responding. I don't program PHP and prefer command line tools over web tools. I will probably write myself a nice C command line tool to manage this. I avoid using Adafruit's stuff (I write my own) and don't expect that they would fix this, so I'll just have to manage this for my own projects. I'm working on a CO2/Clock project that needs large digits and this is why I bumped into this issue.

![20240521_100430](https://github.com/ropg/truetype2gfx/assets/9803883/670dc37b-b510-46e5-824c-f46bc6f38a7d)
